require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5.0
  Exclude:
    - bin/**/*
    - config/**/*
    - vendor/**/*
    - db/**/*
    - Rakefile

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*
    
Metrics/LineLength:
  Max: 120